enable_debug_for_admins:
  type: bool
  default: true
  description: ""
enable_debug_for_all:
  type: bool
  default: false
  description: ""
enable_component_only_for_admins:
  type: bool
  default: true
  description: "disable to make this component visible to Non Admins (All users)"
